//! Vault directory-layout enforcement.
//!
//! [`ensure_layout`] creates the unwarp-managed subdirectories under a vault
//! root: `brew/`, `projects/`, `runbooks/`, and `.unwarp/`. It NEVER creates,
//! reads, or modifies anything under `notes/` — that's the user's
//! free-form workspace and the app must leave it alone (PRD §4.7).
//!
//! [`is_under_notes`] is the boundary check: any vault-write code path must
//! call it on its target path before touching the filesystem.

use std::io;
use std::path::Path;

use thiserror::Error;

/// Subdirectory the user owns; the app must never touch its contents.
pub const NOTES_DIR_NAME: &str = "notes";

/// unwarp-managed subdirectories. `notes/` is intentionally absent.
const MANAGED_SUBDIRS: &[&str] = &["brew", "projects", "runbooks", ".unwarp"];

/// Default content for `brew/_index.md`. Regenerated by the brew job; this
/// only fills in the file if it doesn't exist yet.
const BREW_INDEX_TEMPLATE: &str = "\
# Homebrew formulae

This index is regenerated by the unwarp brew docs job.
Run the job from the Ollama / Vault sidebar to populate it.
";

/// Default content for `projects/_index.md`.
const PROJECTS_INDEX_TEMPLATE: &str = "\
# Projects

Project READMEs, AGENTS.md, and CLAUDE.md files mirrored from your
filesystem appear here as `*.mirror.md` files. Edit `notes.md` next to
them for free-form notes.
";

/// Errors produced while creating the vault layout.
#[derive(Debug, Error)]
pub enum LayoutError {
    /// Filesystem error while creating a directory or writing an index file.
    #[error("filesystem error at {path}: {source}")]
    Io {
        path: String,
        #[source]
        source: io::Error,
    },

    /// The given root is not a directory (or doesn't exist and we couldn't
    /// create it).
    #[error("vault root is not a directory: {0}")]
    NotADirectory(String),
}

/// Idempotently create the unwarp-managed subdirectories under `root`.
///
/// - Creates `root` itself if missing.
/// - Creates `brew/`, `projects/`, `runbooks/`, `.unwarp/` if missing.
/// - Writes `brew/_index.md` and `projects/_index.md` if they don't exist.
/// - Does NOT create `notes/` — the user creates that on their own when (and
///   if) they want it.
/// - Does NOT touch anything that already exists.
pub fn ensure_layout(root: &Path) -> Result<(), LayoutError> {
    if root.as_os_str().is_empty() {
        return Err(LayoutError::NotADirectory(String::new()));
    }

    if !root.exists() {
        std::fs::create_dir_all(root).map_err(|e| LayoutError::Io {
            path: root.display().to_string(),
            source: e,
        })?;
    } else if !root.is_dir() {
        return Err(LayoutError::NotADirectory(root.display().to_string()));
    }

    for subdir in MANAGED_SUBDIRS {
        let path = root.join(subdir);
        if !path.exists() {
            std::fs::create_dir_all(&path).map_err(|e| LayoutError::Io {
                path: path.display().to_string(),
                source: e,
            })?;
        }
    }

    write_if_absent(&root.join("brew/_index.md"), BREW_INDEX_TEMPLATE)?;
    write_if_absent(&root.join("projects/_index.md"), PROJECTS_INDEX_TEMPLATE)?;

    Ok(())
}

fn write_if_absent(path: &Path, content: &str) -> Result<(), LayoutError> {
    if path.exists() {
        return Ok(());
    }
    std::fs::write(path, content).map_err(|e| LayoutError::Io {
        path: path.display().to_string(),
        source: e,
    })
}

/// Returns `true` if `path` is the `notes/` directory itself or any descendant.
///
/// Use as a precondition in any code that writes, deletes, or otherwise
/// modifies a vault file. The vault explorer panel uses this same check to
/// disable in-app edit affordances on user-owned content.
pub fn is_under_notes(vault_root: &Path, path: &Path) -> bool {
    let notes_root = vault_root.join(NOTES_DIR_NAME);
    path == notes_root.as_path() || path.starts_with(&notes_root)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn ensure_layout_creates_managed_subdirs() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        ensure_layout(root).unwrap();
        for subdir in MANAGED_SUBDIRS {
            assert!(
                root.join(subdir).is_dir(),
                "expected {subdir}/ to exist after ensure_layout"
            );
        }
    }

    #[test]
    fn ensure_layout_does_not_create_notes_dir() {
        let dir = tempfile::tempdir().unwrap();
        ensure_layout(dir.path()).unwrap();
        assert!(
            !dir.path().join(NOTES_DIR_NAME).exists(),
            "ensure_layout must not create notes/ — that's user-owned"
        );
    }

    #[test]
    fn ensure_layout_writes_index_templates() {
        let dir = tempfile::tempdir().unwrap();
        ensure_layout(dir.path()).unwrap();
        assert!(dir.path().join("brew/_index.md").is_file());
        assert!(dir.path().join("projects/_index.md").is_file());
    }

    #[test]
    fn ensure_layout_is_idempotent() {
        let dir = tempfile::tempdir().unwrap();
        ensure_layout(dir.path()).unwrap();
        // Second call must succeed and not clobber existing files.
        let custom = "user content here";
        std::fs::write(dir.path().join("brew/_index.md"), custom).unwrap();
        ensure_layout(dir.path()).unwrap();
        assert_eq!(
            std::fs::read_to_string(dir.path().join("brew/_index.md")).unwrap(),
            custom,
            "ensure_layout overwrote an existing user-modified file"
        );
    }

    #[test]
    fn ensure_layout_creates_root_if_missing() {
        let parent = tempfile::tempdir().unwrap();
        let root = parent.path().join("nested/new-vault");
        assert!(!root.exists());
        ensure_layout(&root).unwrap();
        assert!(root.is_dir());
        assert!(root.join("brew").is_dir());
    }

    #[test]
    fn ensure_layout_rejects_when_root_is_a_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("not-a-dir");
        std::fs::write(&path, "hello").unwrap();
        let err = ensure_layout(&path).unwrap_err();
        assert!(matches!(err, LayoutError::NotADirectory(_)));
    }

    #[test]
    fn is_under_notes_matches_notes_subtree() {
        let root = PathBuf::from("/vault");
        assert!(is_under_notes(&root, &root.join("notes")));
        assert!(is_under_notes(&root, &root.join("notes/sub/file.md")));
    }

    #[test]
    fn is_under_notes_rejects_other_subtrees() {
        let root = PathBuf::from("/vault");
        assert!(!is_under_notes(&root, &root.join("brew")));
        assert!(!is_under_notes(&root, &root.join("brew/jq.md")));
        assert!(!is_under_notes(&root, &root.join("projects/foo/notes.md")));
        // sibling directory that happens to contain "notes" in its name
        assert!(!is_under_notes(&root, &root.join("notes-archive/old.md")));
    }
}
