//! Brew docs job implementation.
//!
//! Workflow on `BrewJob::run`:
//! 1. Shell out to `brew info --json=v2 --installed` (one call, all formulae).
//! 2. Parse the JSON into [`FormulaInfo`].
//! 3. For each formula: render markdown → write `<vault>/brew/<name>.md`.
//!    Skip writes where the file already has identical content
//!    (sha256-equality) to avoid touching mtimes the indexer watches.
//! 4. Sweep `<vault>/brew/*.md` and delete files whose formula is no longer
//!    installed (preserving `_index.md` and any user-created files).
//! 5. Regenerate `_index.md` with the current formula table.
//!
//! Casks are out of scope for v1 (formulae only).

use std::collections::HashSet;
use std::io;
use std::path::{Path, PathBuf};

use serde::Deserialize;
use sha2::{Digest, Sha256};
use thiserror::Error;
use tokio::process::Command;

const BREW_BINARY: &str = "brew";
const INDEX_FILENAME: &str = "_index.md";
const BREW_GENERATED_HEADER: &str =
    "<!-- AUTO-GENERATED by unwarp brew docs job. Manual edits will be overwritten. -->\n\n";

/// Errors produced by the brew job.
#[derive(Debug, Error)]
pub enum BrewError {
    #[error("Homebrew is not installed (`brew` not found in PATH)")]
    NotInstalled,

    #[error("`brew info` exited {status}: {stderr}")]
    CommandFailed { status: i32, stderr: String },

    #[error("could not parse `brew info` JSON: {0}")]
    Json(String),

    #[error("filesystem error at {path}: {source}")]
    Io {
        path: String,
        #[source]
        source: io::Error,
    },
}

/// Per-run summary returned by [`BrewJob::run`].
#[derive(Debug, Default, Clone)]
pub struct BrewJobReport {
    pub written: Vec<String>,
    pub skipped: Vec<String>,
    pub deleted: Vec<String>,
    pub errors: Vec<(String, String)>, // (formula, error message)
}

/// One formula's brew info, slimmed down to fields we render.
#[derive(Debug, Clone, Deserialize)]
struct FormulaInfo {
    name: String,
    #[serde(default)]
    desc: Option<String>,
    #[serde(default)]
    homepage: Option<String>,
    #[serde(default)]
    versions: VersionInfo,
    #[serde(default)]
    caveats: Option<String>,
}

#[derive(Debug, Clone, Default, Deserialize)]
struct VersionInfo {
    #[serde(default)]
    stable: Option<String>,
}

#[derive(Debug, Deserialize)]
struct BrewInfoEnvelope {
    #[serde(default)]
    formulae: Vec<FormulaInfo>,
}

/// Brew docs job, parameterized by the vault root. The `<root>/brew/`
/// subdirectory is assumed to exist (created by [`crate::vault::ensure_layout`]).
#[derive(Debug, Clone)]
pub struct BrewJob {
    vault_root: PathBuf,
}

impl BrewJob {
    pub fn new(vault_root: PathBuf) -> Self {
        Self { vault_root }
    }

    /// Run the full job. Returns a report of what was written / skipped /
    /// deleted / errored. Per-formula errors do NOT abort the run; they're
    /// collected in the report.
    pub async fn run(&self) -> Result<BrewJobReport, BrewError> {
        let raw_json = run_brew_info_installed().await?;
        let envelope: BrewInfoEnvelope = serde_json::from_str(&raw_json)
            .map_err(|e| BrewError::Json(e.to_string()))?;

        let brew_dir = self.vault_root.join("brew");
        let mut report = BrewJobReport::default();
        let mut current_names: HashSet<String> = HashSet::new();

        for formula in &envelope.formulae {
            current_names.insert(formula.name.clone());
            let target = brew_dir.join(formula_filename(&formula.name));
            let new_content = render_formula_markdown(formula);

            match write_if_changed(&target, &new_content) {
                Ok(WriteOutcome::Written) => report.written.push(formula.name.clone()),
                Ok(WriteOutcome::Unchanged) => report.skipped.push(formula.name.clone()),
                Err(e) => report
                    .errors
                    .push((formula.name.clone(), e.to_string())),
            }
        }

        // Sweep the brew/ directory for stale .md files corresponding to
        // formulae that are no longer installed. Preserve the index, any
        // non-.md files the user has dropped in, and any *.md whose stem
        // isn't a known formula filename pattern.
        match sweep_stale(&brew_dir, &current_names) {
            Ok(deleted) => report.deleted = deleted,
            Err(e) => report
                .errors
                .push(("<sweep>".to_string(), e.to_string())),
        }

        // Regenerate the index. Ignore failures — written/skipped report is
        // the user-visible value; index is convenience.
        let index_path = brew_dir.join(INDEX_FILENAME);
        let index_content = render_index(&envelope.formulae);
        if let Err(e) = write_if_changed(&index_path, &index_content) {
            report
                .errors
                .push((INDEX_FILENAME.to_string(), e.to_string()));
        }

        Ok(report)
    }
}

/// Run `brew info --json=v2 --installed` and return stdout as a string.
async fn run_brew_info_installed() -> Result<String, BrewError> {
    let output = Command::new(BREW_BINARY)
        .args(["info", "--json=v2", "--installed"])
        .output()
        .await
        .map_err(|e| {
            if e.kind() == io::ErrorKind::NotFound {
                BrewError::NotInstalled
            } else {
                BrewError::Io {
                    path: BREW_BINARY.into(),
                    source: e,
                }
            }
        })?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr).to_string();
        return Err(BrewError::CommandFailed {
            status: output.status.code().unwrap_or(-1),
            stderr,
        });
    }

    String::from_utf8(output.stdout)
        .map_err(|e| BrewError::Json(format!("non-UTF8 stdout from brew: {e}")))
}

/// Render the per-formula markdown body.
fn render_formula_markdown(f: &FormulaInfo) -> String {
    let mut s = String::from(BREW_GENERATED_HEADER);
    s.push_str(&format!("# {}\n\n", f.name));

    let version = f.versions.stable.as_deref().unwrap_or("(unknown version)");
    let desc = f.desc.as_deref().unwrap_or("(no description)");
    s.push_str(&format!("`{}` v{} — {}\n\n", f.name, version, desc));

    if let Some(homepage) = &f.homepage {
        s.push_str(&format!("- Homepage: <{}>\n", homepage));
    }

    if let Some(caveats) = &f.caveats {
        s.push_str("\n## Caveats\n\n");
        s.push_str(caveats.trim());
        s.push('\n');
    }

    s
}

/// Render `brew/_index.md` with a sortable table of all installed formulae.
fn render_index(formulae: &[FormulaInfo]) -> String {
    let mut s = String::from(BREW_GENERATED_HEADER);
    s.push_str("# Homebrew formulae\n\n");
    s.push_str(&format!(
        "{} formulae installed.\n\n",
        formulae.len()
    ));
    s.push_str("| Formula | Version | Description |\n");
    s.push_str("|---|---|---|\n");

    let mut sorted: Vec<&FormulaInfo> = formulae.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));
    for f in sorted {
        let version = f.versions.stable.as_deref().unwrap_or("");
        let desc = f
            .desc
            .as_deref()
            .unwrap_or("")
            .replace('|', r"\|")
            .replace('\n', " ");
        s.push_str(&format!(
            "| [{name}]({name}.md) | {version} | {desc} |\n",
            name = f.name,
        ));
    }
    s
}

/// Filename for a formula. Brew formula names are restricted to
/// `[a-z0-9@+-_.]+` so they're safe as filenames; we don't sanitize.
fn formula_filename(name: &str) -> String {
    format!("{name}.md")
}

/// Write `content` to `path` only if the existing file's content differs.
/// Skips the write (and avoids bumping mtime) when content is identical.
fn write_if_changed(path: &Path, content: &str) -> Result<WriteOutcome, BrewError> {
    let new_hash = sha256_str(content);
    if let Ok(existing) = std::fs::read_to_string(path) {
        if sha256_str(&existing) == new_hash {
            return Ok(WriteOutcome::Unchanged);
        }
    }
    std::fs::write(path, content).map_err(|e| BrewError::Io {
        path: path.display().to_string(),
        source: e,
    })?;
    Ok(WriteOutcome::Written)
}

#[derive(Debug, PartialEq, Eq)]
enum WriteOutcome {
    Written,
    Unchanged,
}

fn sha256_str(s: &str) -> [u8; 32] {
    let mut h = Sha256::new();
    h.update(s.as_bytes());
    h.finalize().into()
}

/// Delete `<brew_dir>/<name>.md` files whose `<name>` is not in `current_names`.
/// Preserves `_index.md` and ignores non-`.md` files.
fn sweep_stale(
    brew_dir: &Path,
    current_names: &HashSet<String>,
) -> Result<Vec<String>, BrewError> {
    let mut deleted = Vec::new();
    let entries = match std::fs::read_dir(brew_dir) {
        Ok(e) => e,
        // If the dir doesn't exist, there's nothing to sweep.
        Err(e) if e.kind() == io::ErrorKind::NotFound => return Ok(deleted),
        Err(e) => {
            return Err(BrewError::Io {
                path: brew_dir.display().to_string(),
                source: e,
            })
        }
    };

    for entry in entries.flatten() {
        let path = entry.path();
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        if name == INDEX_FILENAME {
            continue;
        }
        let Some(stem) = name.strip_suffix(".md") else {
            continue;
        };
        if current_names.contains(stem) {
            continue;
        }
        // Stale formula file. Only delete files that look generated (start
        // with our header sentinel) so we never blow away user-authored
        // content the user may have dropped in.
        if !is_generated_file(&path) {
            continue;
        }
        if let Err(e) = std::fs::remove_file(&path) {
            return Err(BrewError::Io {
                path: path.display().to_string(),
                source: e,
            });
        }
        deleted.push(stem.to_string());
    }
    Ok(deleted)
}

fn is_generated_file(path: &Path) -> bool {
    match std::fs::read_to_string(path) {
        Ok(s) => s.starts_with(BREW_GENERATED_HEADER.trim_end()),
        Err(_) => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn formula(name: &str, version: &str, desc: Option<&str>, caveats: Option<&str>) -> FormulaInfo {
        FormulaInfo {
            name: name.to_owned(),
            desc: desc.map(str::to_owned),
            homepage: Some(format!("https://example.com/{name}")),
            versions: VersionInfo {
                stable: Some(version.to_owned()),
            },
            caveats: caveats.map(str::to_owned),
        }
    }

    #[test]
    fn render_formula_markdown_includes_name_version_desc_homepage() {
        let f = formula("jq", "1.7", Some("CLI JSON processor"), None);
        let md = render_formula_markdown(&f);
        assert!(md.contains("# jq"));
        assert!(md.contains("`jq` v1.7"));
        assert!(md.contains("CLI JSON processor"));
        assert!(md.contains("https://example.com/jq"));
        assert!(!md.contains("## Caveats"));
        assert!(md.starts_with(BREW_GENERATED_HEADER));
    }

    #[test]
    fn render_formula_markdown_includes_caveats_when_present() {
        let f = formula(
            "dotnet",
            "9.0",
            Some(".NET runtime"),
            Some("Set DOTNET_ROOT in your shell profile."),
        );
        let md = render_formula_markdown(&f);
        assert!(md.contains("## Caveats"));
        assert!(md.contains("Set DOTNET_ROOT"));
    }

    #[test]
    fn render_formula_markdown_handles_missing_optional_fields() {
        let mut f = formula("mystery", "0.1", None, None);
        f.homepage = None;
        f.versions.stable = None;
        let md = render_formula_markdown(&f);
        assert!(md.contains("(no description)"));
        assert!(md.contains("(unknown version)"));
        assert!(!md.contains("Homepage"));
    }

    #[test]
    fn render_index_has_table_with_one_row_per_formula() {
        let formulae = vec![
            formula("ripgrep", "14.1.0", Some("grep replacement"), None),
            formula("jq", "1.7", Some("CLI JSON processor"), None),
        ];
        let idx = render_index(&formulae);
        assert!(idx.contains("# Homebrew formulae"));
        assert!(idx.contains("2 formulae installed"));
        assert!(idx.contains("[jq](jq.md)"));
        assert!(idx.contains("[ripgrep](ripgrep.md)"));
        // Sorted alphabetically: jq before ripgrep
        assert!(idx.find("jq.md").unwrap() < idx.find("ripgrep.md").unwrap());
    }

    #[test]
    fn render_index_escapes_pipes_in_descriptions() {
        let f = formula("weird", "1.0", Some("does | this | matter"), None);
        let idx = render_index(&[f]);
        // Pipes must be backslash-escaped to not break the markdown table.
        assert!(idx.contains(r"does \| this \| matter"));
    }

    #[test]
    fn write_if_changed_skips_when_content_identical() {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("x.md");
        let content = "hello";
        assert_eq!(
            write_if_changed(&p, content).unwrap(),
            WriteOutcome::Written
        );
        let mtime_before = std::fs::metadata(&p).unwrap().modified().unwrap();
        // Sleep briefly so modified() would change if we did write.
        std::thread::sleep(std::time::Duration::from_millis(10));
        assert_eq!(
            write_if_changed(&p, content).unwrap(),
            WriteOutcome::Unchanged
        );
        let mtime_after = std::fs::metadata(&p).unwrap().modified().unwrap();
        assert_eq!(mtime_before, mtime_after, "should not bump mtime");
    }

    #[test]
    fn write_if_changed_writes_when_content_differs() {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("x.md");
        write_if_changed(&p, "first").unwrap();
        assert_eq!(
            write_if_changed(&p, "second").unwrap(),
            WriteOutcome::Written
        );
        assert_eq!(std::fs::read_to_string(&p).unwrap(), "second");
    }

    #[test]
    fn sweep_stale_removes_generated_files_for_uninstalled_formulae() {
        let dir = tempfile::tempdir().unwrap();
        // Plant a generated formula file, the index, a generated file for an
        // uninstalled formula, and a user-authored markdown file.
        let installed = "jq.md";
        let stale = "ripgrep.md";
        let user_authored = "my-notes.md";
        std::fs::write(
            dir.path().join(installed),
            format!("{BREW_GENERATED_HEADER}# jq"),
        )
        .unwrap();
        std::fs::write(
            dir.path().join(stale),
            format!("{BREW_GENERATED_HEADER}# ripgrep"),
        )
        .unwrap();
        std::fs::write(dir.path().join(INDEX_FILENAME), "# index").unwrap();
        std::fs::write(dir.path().join(user_authored), "# my notes (no header)").unwrap();

        let current: HashSet<String> = ["jq".into()].into_iter().collect();
        let deleted = sweep_stale(dir.path(), &current).unwrap();

        assert_eq!(deleted, vec!["ripgrep".to_string()]);
        assert!(dir.path().join(installed).exists());
        assert!(!dir.path().join(stale).exists());
        assert!(dir.path().join(INDEX_FILENAME).exists());
        assert!(
            dir.path().join(user_authored).exists(),
            "user-authored files (no generated header) must be preserved"
        );
    }

    #[test]
    fn sweep_stale_handles_missing_dir() {
        let deleted = sweep_stale(Path::new("/definitely/not/here"), &HashSet::new()).unwrap();
        assert!(deleted.is_empty());
    }

    /// Live integration test: runs the full job against the user's real brew
    /// install, writing to a tempdir-scoped vault. Ignored by default.
    /// Run with: cargo test -p warp -- --ignored vault::brew::job::tests::live_brew_run
    #[tokio::test]
    #[ignore]
    async fn live_brew_run() {
        let dir = tempfile::tempdir().unwrap();
        let vault_root = dir.path().to_owned();
        std::fs::create_dir_all(vault_root.join("brew")).unwrap();
        let job = BrewJob::new(vault_root.clone());
        let report = job
            .run()
            .await
            .expect("expected brew job to succeed against real Homebrew");
        // Should have written at least one .md file (assuming user has any
        // formulae installed). Index should also exist.
        assert!(
            !report.written.is_empty() || !report.skipped.is_empty(),
            "expected some formula files in the report; got {report:?}"
        );
        assert!(vault_root.join("brew").join(INDEX_FILENAME).exists());
        // Errors should be empty for a normal install.
        assert!(report.errors.is_empty(), "unexpected errors: {:?}", report.errors);
    }
}
